Support LDAP authentication and authrorization
tcpcloud/salt-formula-nagios pull request #8
Opened 2016-12-05 15:40 UTC by SwannCroiset

Can be tested by installing OpenLdap with the StackLight script [0]  on node **cfg01** and with this user data (pillar) :

nagios:server:ui:ldap_authnz:

>   url: ldap://cfg01/dc=stacklight,dc=ci?uid?sub?(objectClass=*)
>   bind_dn: cn=admin,dc=stacklight,dc=ci 
>   bind_password: admin
>   ldap_group_dn: cn=plugin_admins,ou=groups,dc=stacklight,dc=ci
>   ldap_group_attribute: memberUid

[0] https://raw.githubusercontent.com/openstack/stacklight-integration-tests/master/fixtures/ldap/install_slapd.sh

2016-12-06 10:29 UTC, simonpasquier requested changes

2016-12-06 10:29 UTC, simonpasquier commented on README.rst
> +            ldap_group_attribute: memberUid
It might be clearer to have a `auth` top key and then `basic` and `ldap`?

```
  auth:
    ldap:
      ...
    basic:
      ...
```

2016-12-06 10:29 UTC, simonpasquier commented on nagios/server.sls
> +{%- if server.ui.get('ldap_authnz') is mapping and server.ui.ldap_authnz.url is defined %}
`if server.ui.get('ldap_authnz', {}).url is defined`?

2016-12-06 10:29 UTC, simonpasquier commented on nagios/files/nagios.conf.Debian
> +    {%- if server.ui.get('ldap_authnz') is mapping and server.ui.ldap_authnz.url is defined %}
`if server.ui.get('ldap_authnz', {}).url is defined`?

2016-12-06 12:50 UTC, SwannCroiset commented on README.rst
> +            ldap_group_attribute: memberUid
@simonpasquier done

2016-12-06 13:00 UTC, elemoine approved these changes

2016-12-06 13:00 UTC, elemoine commented on README.rst
> +Nagios UI configrations with LDAP authentication/authorization:
s/configrations/configuration

2016-12-07 09:07 UTC, simonpasquier approved these changes

2016-12-07 09:26 UTC, merged